---
title: "Miletone_No_4"
author: "Patrick Traynor, Ph.D., R.D., Virginia Chan, Antoinette Stetzenmeyer"
date: "11/11/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# First Task: Three or More Visualizations
## One print quality table as requested in Scenario

```{r}
#import data sets
library(readr)
ca_county_demographics <- read_csv("ca_county_demographics.csv")
cov_vax_admin <- read_csv("cov_vax_admin.csv")

```
```{r}
#First select columns needed from cov_vax_admin
library(magrittr)
library(tidyverse)
cov_vax_admin_1 <- cov_vax_admin %>%
  select (as_of_date, zip_code_tabulation_area, 
county, persons_fully_vaccinated, age12_plus_population)
```
```{r}
#get unique dates to select the most recent:
library(lubridate)
date <- mdy(unique(cov_vax_admin$as_of_date))
sort(date)

unique(cov_vax_admin$as_of_date)
cov_vax_admin_2 <- cov_vax_admin_1 %>%
  filter(as_of_date == "9/14/2021")
         
# calculate average vaccination rate by county
# Your task is to explore the Vaccine Progress Dashboard and locate the most recent vaccination data, including a percentage of fully vaccinated persons. If you find any missing values, you'll need to find a way to do *mean imputation* with the missing values on a zip code level, (substitute an average value to fill in the NAs values from the county level averages)



#get the mean rate for each county

means_by_county <- cov_vax_admin_2 %>% 
  group_by(county) %>%
  summarize(mean = mean(persons_fully_vaccinated, na.rm = T))

# Remove NA counties because we don't know which county they are 
cov_vax_admin_2 <- cov_vax_admin_2 %>% 
  drop_na(county)

#check to see if there are any NA's
table(is.na(cov_vax_admin_2$persons_fully_vaccinated))
#yes there are

# Inner join mean values into the cov_vax_admin_2 table
cov_vax_admin_3 <- inner_join(cov_vax_admin_2, means_by_county,
              by = "county")

cov_vax_admin_4 <- cov_vax_admin_3 %>% 
  mutate(num_fully_vax_wo_NA = if_else(is.na(persons_fully_vaccinated),
                                    mean,
                                    persons_fully_vaccinated))
  
```
```{r}
table(is.na(cov_vax_admin_4$age12_plus_population))
#there are no more NAs
```
```{r}
# Get the rate of vaccination
cov_vax_admin_5 <- cov_vax_admin_4 %>% 
  group_by(county) %>%
  summarize(total_vax = sum(num_fully_vax_wo_NA),
            total_pop = sum(age12_plus_population),
            rate = round((total_vax/total_pop)*100, 2))

head(cov_vax_admin_5)
```

```{r}
#Antoinette code

total_pop <- ca_county_demographics %>%
  select(name, pop2012, med_age) %>% 
  mutate(name=str_to_upper(name))

merged_median_age_cov_vax <-  inner_join(cov_vax_admin_5, total_pop, by=c("county"="name"))
```




```{r}
install.packages("DT")
library("DT")
#make sure we put a title on this
datatable(cov_vax_admin_5, 
          options = list(
            pageLength=5,
            lengthMenu=c(5,10,15,58),
            order=list(4,'desc'),
            columnDefs=list(
              list(className='dt-center',targets=2:4)
              )
            ),
            colnames=c("County","Total Vaccinated","Total Population","Vaccination Rate"),
            filter="top"
          ) %>%
          formatRound(2:4,2) %>%
  formatStyle(1,color="blue")

# cov_vax_admin_3 <- cov_vax_admin_2 %>%
#   group_by(county) %>%
#   summarize(mean_vax = mean(persons_fully_vaccinated, na.rm = T))
# 
# #first determine "percentage of fully vaccinated persons."
# cov_vax_admin_3 <-cov_vax_admin_2 %>%
#   mutate(pct_fully_vax = round((
#     persons_fully_vaccinated/age12_plus_population)*100,2))

#get the mean rate for each county

# mean_county_vax_rate <- cov_vax_admin_3 %>%
#   group_by(county) %>%
#   summarize(mean_vax_rate = mean(pct_fully_vax, na.rm = T))


```
Median age vs. percentage of vaccination

In this block of the analysis we will join the demographic dataset with the percentage of vaccinated persons dataset.
```{r}
# Set county names of cov_demographics to uppercase, 
# and select wanted columns
ca_county_demographics_up <- ca_county_demographics %>% 
  mutate(uppercase_county = toupper(name)) %>%
  select(uppercase_county, med_age)



joined_cov_vax_rate_med_age <- inner_join(cov_vax_admin_5,
                                          ca_county_demographics_up, 
           by = c("county" = "uppercase_county"))%>%
           arrange(med_age)
```
```{r}
# don't need legend, just make it clear what every means in either the caption 
# or the title
joined_cov_vax_rate_med_age %>%
  ggplot(aes(x = rate, y = med_age)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  theme_bw() +
  xlab("Prevalence of COVID vaccination") +
  ylab("Median age") +
  ggtitle("Prevalence of COVID \nvaccination rate and mean age\n by county of California") +
  labs(caption = "Note: The above data show as California county\n median age increases the prevalence \n of COVID-19 vaccination increases.")
```
We can put narrative here
```{r}
#clean up axis titles
#include description
#actually, I just ordered the plot in the code that follows this one. Patrick 
 # joined_cov_vax_rate_med_age %>%
 #  ggplot(aes(county, med_age, fill = county)) +
 #  geom_bar(stat = "identity", 
 #           position = position_dodge()) + 
 #  coord_flip() +
 #  guides(fill = guide_legend(title = "")) 

joined_cov_vax_rate_med_age %>%
  arrange(med_age) %>%
  mutate(county_ordered = factor(county,
                                 levels = county,
                                 labels = county,
                                 ordered = T)) %>%
  ggplot(aes(county_ordered, med_age, fill = county_ordered)) +
  geom_bar(stat = "identity", 
           position = position_dodge()) + 
  guides(fill = guide_legend(reverse = TRUE)) +
  coord_flip() + 
  theme(legend.position = "none")


```

